MvcProjeKampi/Controllers/AdminCategoryController.cs
using BusinessLayer.Concrete;
using BusinessLayer.ValidationRules;
using DataAccessLayer.EntityFramework;
using EntityLayer.Concrete;
using FluentValidation.Results;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace MvcProjeKampi.Controllers
{
    public class AdminCategoryController : Controller
    {
        CategoryManager cm = new CategoryManager(new EFCategoryDal());
        public ActionResult Index()
        {
            var catValues = cm.GetCategories();
            return View(catValues);
        }
        [HttpGet]
        public ActionResult AddCategory()
        {
            return View();
        }
        [HttpPost]
        public ActionResult AddCategory(Category P)
        {
            categoryValidator CV = new categoryValidator();
            ValidationResult results = CV.Validate(P);
            if (results.IsValid)
            {
                cm.CategoryAdd(P);
                return RedirectToAction("Index");
            }
            else
            {
                foreach (var item in results.Errors)
                {
                    ModelState.AddModelError(item.PropertyName, item.ErrorMessage);
                }
            }
            return View();
        }

        public ActionResult DelCategory(int id)
        {
            var catValues = cm.getbyID(id);
            cm.DelCategory(catValues);
            return RedirectToAction("Index");
        }
        [HttpGet]
        public ActionResult UpdateCategory(int id)
        {
            var catValues = cm.getbyID(id);
            return View(catValues);
        }
        [HttpPost]
        public ActionResult UpdateCategory(Category T)
        {
            cm.UpdateCategory(T);
            return RedirectToAction("Index");
        }
    }
}

MvcProjeKampi/Controllers/CategoryController.cs
using BusinessLayer.Concrete;
using BusinessLayer.ValidationRules;
using DataAccessLayer.EntityFramework;
using EntityLayer.Concrete;
using FluentValidation.Results;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace MvcProjeKampi.Controllers
{
    public class CategoryController : Controller
    {
        // GET: Category
        CategoryManager cm = new CategoryManager(new EFCategoryDal());
        public ActionResult Index()
        {
            return View();
        }
        public ActionResult GetCategoryList()
        {
            var CatValues = cm.GetCategories();
            return View(CatValues);
        }
        [HttpGet]
        public ActionResult AddCategory()
        {            
            return View();
        }
        [HttpPost]
        public ActionResult AddCategory(Category Cat)
        {
            categoryValidator categoryValidator = new categoryValidator();
            ValidationResult result = categoryValidator.Validate(Cat);
            if(result.IsValid)
            {               
                cm.CategoryAdd(Cat);
                return RedirectToAction("GetCategoryList");
            }
            else
            {
                foreach (var item in result.Errors)
                {
                    ModelState.AddModelError(item.PropertyName,item.ErrorMessage);
                }
            }
            return View();
        }
    }   
}

MvcProjeKampi/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace MvcProjeKampi.Controllers
{
    public class HomeController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult About()
        {
            ViewBag.Message = "Your application description page.";

            return View();
        }

        public ActionResult Contact()
        {
            ViewBag.Message = "Your contact page.";

            return View();
        }
        public ActionResult Test()
        {
            ViewBag.Message = "My Name Is : ";
            return View();
        }
    }
}

MvcProjeKampi/Controllers/TestController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace MvcProjeKampi.Controllers
{
    public class TestController : Controller
    {
        // GET: Test
        public ActionResult Index()
        {
            return View();
        }
        public ActionResult Index2()
        {
            return View();
        }
    }
}

MvcProjeKampi/Views/AdminCategory/AddCategory.cshtml
@model EntityLayer.Concrete.Category
@{
    ViewBag.Title = "AddCategory";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}
<link href="~/Content/bootstrap.min.css" rel="stylesheet" />

<h1>Yeni Kategori Ekle</h1>

@using (Html.BeginForm("AddCategory", "AdminCategory", FormMethod.Post))
{
    <div class="form-group position-relative">
        @Html.Label("Kategori Adı : ")
        @Html.TextBoxFor(x => x.CategoryName, new { @class = "form-control" })
        @Html.ValidationMessageFor(x => x.CategoryName)
        <br /><br />
        @Html.Label("Açıklama : ")
        @Html.TextAreaFor(x => x.CategoryDesc, new { @class = "form-control position-relative" })
        @Html.ValidationMessageFor(x => x.CategoryDesc)
        <br />
        <br />
        <button class="btn btn-success rounded-pill">Kategoriyi Kaydet</button>
    </div>
}

MvcProjeKampi/Views/AdminCategory/Index.cshtml
@using EntityLayer.Concrete
@model List<Category>
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}
<table class="table table-success">
    <tr>
        <th class="text-bg-danger">#</th>
        <th>KATEGORİ ADI</th>
        <th>AÇIKLAMA</th>
        <th>DURUM</th>
        <th>SİL</th>
        <th>GÜNCELLE</th>
        <th>BAŞLIKLAR</th>
    </tr>
    @foreach (var item in Model)
    {
        <tr>
            <th class="text-bg-danger">@item.CategoryID</th>
            <td>@item.CategoryName</td>
            <td>@item.CategoryDesc</td>
            @if (item.CategoryStatus == true)
            {
                <td class="text-bg-success">@item.CategoryStatus</td>
            }
            else
            {
                <td class="text-bg-danger">@item.CategoryStatus</td>
            }
            <td><a href="/AdminCategory/DelCategory/@item.CategoryID" class="btn btn-danger">Sil</a></td>
            <td><a href="/AdminCategory/UpdateCategory/@item.CategoryID" class="btn btn-warning">Güncelle</a></td>
            <td><a href="#" class="btn btn-primary">Başlıklar</a></td>
        </tr>
    }
</table>
<br />
<a href="~/AdminCategory/AddCategory" class="btn btn-primary">Kaydet</a>

MvcProjeKampi/Views/AdminCategory/UpdateCategory.cshtml
@model EntityLayer.Concrete.Category

@{
    ViewBag.Title = "UpdateCategory";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}

<h2>Kategori Güncelleme Sayfası</h2>
<br />
@using (Html.BeginForm("UpdateCategory", "AdminCategory", FormMethod.Post))
{
<div class="form-group">
    @Html.Label("Kategori ID")
    @Html.TextBoxFor(x => x.CategoryID,new { @class ="form-control"})
    <br />
    @Html.Label("Kategori Adı")
    @Html.TextBoxFor(x => x.CategoryName, new { @class = "form-control" })
    <br />
    @Html.Label("Kategori Açıklama")
    @Html.TextAreaFor(x => x.CategoryDesc, new { @class = "form-control" })
    <br />
    <button class="btn btn-success">
        Bilgileri Güncelle
    </button>
</div>
}

MvcProjeKampi/Views/Category/AddCategory.cshtml
@model EntityLayer.Concrete.Category

@{
    Layout = null;
}
<link href="~/Content/bootstrap.min.css" rel="stylesheet" />

<h1>Yeni Kategori Ekle</h1>

@using (Html.BeginForm("AddCategory","Category",FormMethod.Post))
{
<div class="form-group position-absolute">
    @Html.Label("Kategori Adı : ")
    @Html.TextBoxFor(x => x.CategoryName)
    @Html.ValidationMessageFor(x => x.CategoryName)
    <br /><br />
    @Html.Label("Açıklama : ")
    @Html.TextBoxFor(x => x.CategoryDesc)
    @Html.ValidationMessageFor(x => x.CategoryDesc)
    <br />
    <br />
    <button class="btn btn-success rounded-pill">Kategoriyi Kaydet</button>
</div>
}

@*<form class="form-label" method="post">
    <input name="CategoryName" type="text" placeholder="Kategori Adını Buraya Giriniz" class="form-control" />
    <br />
    <input name="CategoryDesc" type="text" placeholder="Kategoriye Ait Açıklamayı Giriniz" class="form-control"/>
    <br />
    <button id="btnEkle" class="btn btn-success">Ekle</button>
    
</form>*@

MvcProjeKampi/Views/Category/GetCategoryList.cshtml
@using EntityLayer.Concrete
@model List<Category>
@{
    Layout = null;
}
<link href="~/Content/bootstrap.min.css" rel="stylesheet" />
<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>GetCategoryList</title>
</head>
<body>
    <div class="position-relative p-5 ">
        <table class="table table-success">
            <tr>
                <th class="text-bg-danger">ID</th>
                <th>ADI</th>
                <th>AÇIKLAMA</th>
                <th>DURUM</th>
            </tr>
            @foreach (var item in Model)
            {
                <tr>
                    <td class="text-bg-danger">@item.CategoryID</td>
                    <td>@item.CategoryName</td>
                    <td>@item.CategoryDesc</td>
                    @if (item.CategoryStatus== true)
                    {
                    <td class="text-bg-success">@item.CategoryStatus</td>
                    }
                    else
                    {
                    <td class="text-bg-danger">@item.CategoryStatus</td>
                    }
                </tr>
            }
        </table>
        <a href="~/Category/AddCategory" class="btn btn-danger">Yeni Kategori Ekle</a>
    </div>
</body>
</html>

MvcProjeKampi/Views/Category/Index.cshtml
@{
    Layout = null;
}
<link href="~/Content/bootstrap.min.css" rel="stylesheet" />

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Index</title>
</head>
<body>
    <h2 style="text-align:center">MVC PROJE KAMPI TABLOSU - KATEGORİ</h2>
    <div class="position-relative p-5">
        <table class="table table-dark table-hover rounded-pill">
            <thead>
                <tr>
                    <th>ID</th>
                    <th>ADI</th>
                    <th>AÇIKLAMA</th>
                    <th>DURUM</th>
                    <th>GÜNCELLE</th>
                </tr>
                <tr>
                    <td>1</td>
                    <td>Eğitim</td>
                    <td>Bu Alanda Egitim Konusulur</td>
                    <td>True</td>
                    <td><button class="btn btn-success rounded-pill">Güncelle</button></td>
                </tr>
                <tr>
                    <td>2</td>
                    <td>Spor</td>
                    <td>Bu Alanda Trabzonspor Vardır</td>
                    <td>True</td>
                    <td><button class="btn btn-success rounded-pill">Güncelle</button></td>
                </tr>
                <tr>
                    <td>3</td>
                    <td>Tiyatro</td>
                    <td>Bu Alanda Tiyotro Konusulur</td>
                    <td>True</td>
                    <td><button class="btn btn-success rounded-pill">Güncelle</button></td>
                </tr>
                <tr>
                    <td>4</td>
                    <td>Sinema</td>
                    <td>Bu Alanda Film Onerileri Vardır</td>
                    <td>True</td>
                    <td><button class="btn btn-success rounded-pill">Güncelle</button></td>
                </tr>
                <tr>
                    <td>5</td>
                    <td>Kitap</td>
                    <td>Bu Alanda Kitap Onerileri Vardır</td>
                    <td>True</td>
                    <td><button class="btn btn-success rounded-pill">Güncelle</button></td>
                </tr>
            </thead>
        </table>
        <button class="btn btn-success rounded-pill">Yeni Kategori Ekle</button>
        <button class="btn btn-primary rounded-pill">Kategori Listesi</button>
        <button class="btn btn-danger rounded-pill">Kategori Açıklamaları</button>

    </div>
</body>
</html>

MvcProjeKampi/Views/Home/About.cshtml
@{
    ViewBag.Title = "About";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<p>Use this area to provide additional information.</p>

MvcProjeKampi/Views/Home/Contact.cshtml
@{
    ViewBag.Title = "Contact";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<address>
    One Microsoft Way<br />
    Redmond, WA 98052-6399<br />
    <abbr title="Phone">P:</abbr>
    425.555.0100
</address>

<address>
    <strong>Support:</strong>   <a href="mailto:Support@example.com">Support@example.com</a><br />
    <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
</address>

MvcProjeKampi/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Home Page";
}

<div class="jumbotron">
    <h1>ASP.NET</h1>
    <p class="lead">ASP.NET is a free web framework for building great Web sites and Web applications using HTML, CSS and JavaScript.</p>
    <p><a href="https://asp.net" class="btn btn-primary btn-lg">Learn more &raquo;</a></p>
</div>

<div class="row">
    <div class="col-md-4">
        <h2>Getting started</h2>
        <p>
            ASP.NET MVC gives you a powerful, patterns-based way to build dynamic websites that
            enables a clean separation of concerns and gives you full control over markup
            for enjoyable, agile development.
        </p>
        <p><a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkId=301865">Learn more &raquo;</a></p>
    </div>
    <div class="col-md-4">
        <h2>Get more libraries</h2>
        <p>NuGet is a free Visual Studio extension that makes it easy to add, remove, and update libraries and tools in Visual Studio projects.</p>
        <p><a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkId=301866">Learn more &raquo;</a></p>
    </div>
    <div class="col-md-4">
        <h2>Web Hosting</h2>
        <p>You can easily find a web hosting company that offers the right mix of features and price for your applications.</p>
        <p><a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkId=301867">Learn more &raquo;</a></p>
    </div>
</div>

MvcProjeKampi/Views/Home/Test.cshtml
@{
    ViewBag.Title = "Test";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Test</h2>
<h1 style="color:lightslategray; font-family:'Agency FB'; font-style:oblique; font-size:xx-large">Ad: Yunus Emre Kobal</h1>

MvcProjeKampi/Views/Shared/LayoutTest.cshtml
@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>LayoutTest</title>
</head>
<body>
    <h1>Selamlar</h1>
    <div class="navbar navbar-collapse navbar-fixed-top">
        <div class="navbar-header">
            
        </div>
        <div class="navbar-collapse collapse">
            <ul class="navbar-nav">
                <li>@Html.ActionLink("Index", "Index", "Test")</li>
                <li>@Html.ActionLink("Index2", "Index2", "Test")</li>
            </ul>

        </div>
    </div>
    <div>
        @RenderBody()
    </div>

</body>
</html>

MvcProjeKampi/Views/Shared/_AdminLayout.cshtml
@{
    Layout = null;
}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="x-ua-compatible" content="ie=edge">
    <title>MVC Proje Kampı</title>
    <!-- Font Awesome Icons -->
    <link rel="stylesheet" href="~/AdminLTE-3.0.4/plugins/fontawesome-free/css/all.min.css">
    <!-- IonIcons -->
    <link rel="stylesheet" href="http://code.ionicframework.com/ionicons/2.0.1/css/ionicons.min.css">
    <!-- Theme style -->
    <link rel="stylesheet" href="~/AdminLTE-3.0.4/dist/css/adminlte.min.css">
    <!-- Google Font: Source Sans Pro -->
    <link href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,400i,700" rel="stylesheet">
</head>
<!--
BODY TAG OPTIONS:
=================
Apply one or more of the following classes to to the body tag
to get the desired effect
|---------------------------------------------------------|
|LAYOUT OPTIONS | sidebar-collapse                        |
|               | sidebar-mini                            |
|---------------------------------------------------------|
-->
<body class="hold-transition sidebar-mini">

    <div class="wrapper">
        <!-- Navbar -->
        <!-- /.navbar -->
        <!-- Main Sidebar Container -->
        <aside class="main-sidebar sidebar-dark-primary elevation-4">
            <!-- Brand Logo -->
            <a href="~/AdminCategory/Index" class="brand-link">
                <img src="~/AdminLTE-3.0.4/dist/img/AdminLTELogo.png" alt="AdminLTE Logo" class="brand-image img-circle elevation-3"
                     style="opacity: .8">
                <span class="brand-text font-weight-light">
                 MVC Proje
                </span>
            </a>
            <!-- Sidebar -->
            <div class="sidebar">
                <!-- Sidebar user panel (optional) -->
                <div class="user-panel mt-3 pb-3 mb-3 d-flex">
                    <div class="image">
                        <img src="~/AdminLTE-3.0.4/dist/img/user2-160x160.jpg" class="img-circle elevation-2" alt="User Image">
                    </div>
                    <div class="info">
                        <a href="~/AdminCategory/Index" class="d-block">Yunus Emre Kobal</a>
                    </div>
                </div>
                <!-- Sidebar Menu -->
                <nav class="mt-2">
                    <ul class="nav nav-pills nav-sidebar flex-column" data-widget="treeview" role="menu" data-accordion="false">
                        <!-- Add icons to the links using the .nav-icon class
                        with font-awesome or any other icon font library -->
                        <li class="nav-item has-treeview menu-open">
                            <a href="#" class="nav-link active">
                                <i class="nav-icon fas fa-tachometer-alt"></i>
                                <p>
                                    Kategoriler
                                </p>
                            </a>

                        </li>
                        <li class="nav-item">
                            <a href="pages/widgets.html" class="nav-link">
                                <i class="nav-icon fas fa-th"></i>
                                <p>
                                    Başlıklar
                                </p>
                            </a>
                        </li>
                        <li class="nav-item has-treeview">
                            <a href="#" class="nav-link">
                                <i class="nav-icon fas fa-copy"></i>
                                <p>
                                    Yazarlar
                                </p>
                            </a>

                        </li>
                        <li class="nav-item has-treeview">
                            <a href="#" class="nav-link">
                                <i class="nav-icon fas fa-chart-pie"></i>
                                <p>
                                    Grafikler
                                    <i class="fas fa-angle-left right"></i>
                                </p>
                            </a>
                            <ul class="nav nav-treeview">
                                <li class="nav-item">
                                    <a href="pages/charts/chartjs.html" class="nav-link">
                                        <i class="far fa-circle nav-icon"></i>
                                        <p>Pasta Dilimi Grafiği</p>
                                    </a>
                                </li>
                                <li class="nav-item">
                                    <a href="pages/charts/flot.html" class="nav-link">
                                        <i class="far fa-circle nav-icon"></i>
                                        <p>Sütun Grafiği</p>
                                    </a>
                                </li>
                                <li class="nav-item">
                                    <a href="pages/charts/inline.html" class="nav-link">
                                        <i class="far fa-circle nav-icon"></i>
                                        <p>Çizgi Grafiği</p>
                                    </a>
                                </li>
                            </ul>
                        </li>
                        <li class="nav-item has-treeview">
                            <a href="#" class="nav-link">
                                <i class="nav-icon fas fa-tree"></i>
                                <p>
                                    Hakkımızda
                                </p>
                            </a>
                        </li>
                        <li class="nav-item has-treeview">
                            <a href="#" class="nav-link">
                                <i class="nav-icon fas fa-edit"></i>
                                <p>
                                    İletişim & Mesajlar
                                </p>
                            </a>
                        </li>
                        <li class="nav-item has-treeview">
                            <a href="#" class="nav-link">
                                <i class="nav-icon fas fa-table"></i>
                                <p>
                                    Yazılar
                                </p>
                            </a>
                        </li>
                        <li class="nav-item has-treeview">
                            <a href="#" class="nav-link">
                                <i class="nav-icon fas fa-calendar-alt"></i>
                                <p>
                                    Yetkilendirmeler
                                </p>
                            </a>
                        </li>
                        <li class="nav-item has-treeview">
                            <a href="#" class="nav-link">
                                <i class="nav-icon fa fa-image"></i>
                                <p>
                                    Galeri
                                </p>
                            </a>
                        </li>
                        <li class="nav-item has-treeview">
                            <a href="#" class="nav-link">
                                <i class="nav-icon fas fa-eraser"></i>
                                <p>
                                    Hata Sayfaları
                                    <i class="fas fa-angle-left right"></i>
                                </p>
                            </a>
                            <ul class="nav nav-treeview">

                            </ul>
                        </li>

                        <li class="nav-item has-treeview">
                            <a href="#" class="nav-link">
                                <i class="nav-icon fas fa-arrow-alt-circle-right"></i>
                                <p>
                                    Siteye Git
                                </p>
                            </a>
                        </li>
                        <li class="nav-item has-treeview">
                            <a href="#" class="nav-link">
                                <i class="nav-icon fas fa-window-close"></i>
                                <p>
                                    Çıkış
                                </p>
                            </a>
                        </li>
                    </ul>
                </nav>
                <!-- /.sidebar-menu -->
            </div>
            <!-- /.sidebar -->
        </aside>
        <!-- Content Wrapper. Contains page content -->
        <div class="content-wrapper">
            <!-- Content Header (Page header) -->
            <div class="content-header">
                <div class="container-fluid">
                    <div class="row mb-2">
                        <div class="col-sm-6">
                            <h1 class="m-0 text-dark">Dashboard</h1>
                        </div><!-- /.col -->
                        <div class="col-sm-6">
                            <ol class="breadcrumb float-sm-right">
                                <li class="breadcrumb-item"><a href="#">Home</a></li>
                                <li class="breadcrumb-item active">Dashboard</li>
                            </ol>
                        </div><!-- /.col -->
                    </div><!-- /.row -->
                </div><!-- /.container-fluid -->
            </div>
            <!-- /.content-header -->
            <!-- Main content -->
            <div class="content">
                @RenderBody()
                <!-- /.container-fluid -->
            </div>
            <!-- /.content -->
        </div>
        <!-- /.content-wrapper -->
        <!-- Control Sidebar -->
        <aside class="control-sidebar control-sidebar-dark">
            <!-- Control sidebar content goes here -->
        </aside>
        <!-- /.control-sidebar -->
        <!-- Main Footer -->

    </div>
    <!-- ./wrapper -->
    <!-- REQUIRED SCRIPTS -->
    <!-- jQuery -->
    <script src="~/AdminLTE-3.0.4/plugins/jquery/jquery.min.js"></script>
    <!-- Bootstrap -->
    <script src="~/AdminLTE-3.0.4/plugins/bootstrap/js/bootstrap.bundle.min.js"></script>
    <!-- AdminLTE -->
    <script src="~/AdminLTE-3.0.4/dist/js/adminlte.js"></script>
    <!-- OPTIONAL SCRIPTS -->
    <script src="~/AdminLTE-3.0.4/plugins/chart.js/Chart.min.js"></script>
    <script src="~/AdminLTE-3.0.4/dist/js/demo.js"></script>
    <script src="~/AdminLTE-3.0.4/dist/js/pages/dashboard3.js"></script>
</body>
</html>

MvcProjeKampi/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Application name", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Home", "Index", "Home")</li>
                    <li>@Html.ActionLink("About", "About", "Home")</li>
                    <li>@Html.ActionLink("Contact", "Contact", "Home")</li>
                    <li>@Html.ActionLink("Test", "Test", "Home")</li>
                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>

MvcProjeKampi/Views/Test/Index.cshtml
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/LayoutTest.cshtml";
}
<h2>Burası Birinci Index Sayfası</h2>

MvcProjeKampi/Views/Test/Index2.cshtml
@{
    ViewBag.Title = "Index2";
    Layout = "~/Views/Shared/LayoutTest.cshtml";
}

<h2>Burası Ikinci Index Sayfası</h2>